# Generated by Django 5.2.9 on 2025-12-30 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversacionChatbot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        blank=True,
                        help_text="Título generado automáticamente del primer mensaje",
                        max_length=200,
                        verbose_name="Título",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha de Creación"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Última Actualización"),
                ),
                ("activa", models.BooleanField(default=True, verbose_name="Conversación Activa")),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversaciones",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conversación",
                "verbose_name_plural": "Conversaciones",
                "db_table": "conversaciones_chatbot",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="MensajeChatbot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "rol",
                    models.CharField(
                        choices=[("user", "Usuario"), ("assistant", "Asistente")],
                        max_length=10,
                        verbose_name="Rol",
                    ),
                ),
                ("contenido", models.TextField(verbose_name="Contenido del Mensaje")),
                ("timestamp", models.DateTimeField(auto_now_add=True, verbose_name="Fecha y Hora")),
                (
                    "conversacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mensajes",
                        to="ia.conversacionchatbot",
                        verbose_name="Conversación",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensaje",
                "verbose_name_plural": "Mensajes",
                "db_table": "mensajes_chatbot",
                "ordering": ["timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="conversacionchatbot",
            index=models.Index(
                fields=["usuario", "-created_at"], name="conversacio_usuario_eb0a08_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mensajechatbot",
            index=models.Index(
                fields=["conversacion", "timestamp"], name="mensajes_ch_convers_360756_idx"
            ),
        ),
    ]
