# Generated by Django 5.2.9 on 2025-12-30 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("productos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Inventario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "cantidad_actual",
                    models.IntegerField(default=0, verbose_name="Cantidad en Stock"),
                ),
                (
                    "ubicacion",
                    models.CharField(
                        blank=True,
                        help_text="Ubicación física en bodega (Ej: A-12-3)",
                        max_length=100,
                        verbose_name="Ubicación",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "producto",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventario",
                        to="productos.producto",
                        verbose_name="Producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventario",
                "verbose_name_plural": "Inventarios",
                "db_table": "inventarios",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MovimientoInventario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("entrada", "Entrada"), ("salida", "Salida")],
                        max_length=20,
                        verbose_name="Tipo de Movimiento",
                    ),
                ),
                ("cantidad", models.IntegerField(verbose_name="Cantidad")),
                ("motivo", models.TextField(blank=True, verbose_name="Motivo")),
                (
                    "fecha",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha del Movimiento"),
                ),
                (
                    "inventario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos",
                        to="inventario.inventario",
                        verbose_name="Inventario",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimiento de Inventario",
                "verbose_name_plural": "Movimientos de Inventario",
                "db_table": "movimientos_inventario",
                "ordering": ["-fecha"],
            },
        ),
        migrations.AddIndex(
            model_name="inventario",
            index=models.Index(fields=["producto"], name="inventarios_product_33b811_idx"),
        ),
        migrations.AddIndex(
            model_name="inventario",
            index=models.Index(fields=["cantidad_actual"], name="inventarios_cantida_2cfef3_idx"),
        ),
        migrations.AddConstraint(
            model_name="inventario",
            constraint=models.CheckConstraint(
                condition=models.Q(("cantidad_actual__gte", 0)), name="cantidad_actual_no_negativa"
            ),
        ),
        migrations.AddIndex(
            model_name="movimientoinventario",
            index=models.Index(
                fields=["inventario", "-fecha"], name="movimientos_inventa_831c40_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="movimientoinventario",
            index=models.Index(fields=["tipo"], name="movimientos_tipo_af40b1_idx"),
        ),
        migrations.AddIndex(
            model_name="movimientoinventario",
            index=models.Index(fields=["fecha"], name="movimientos_fecha_c137fc_idx"),
        ),
        migrations.AddConstraint(
            model_name="movimientoinventario",
            constraint=models.CheckConstraint(
                condition=models.Q(("cantidad__gt", 0)), name="cantidad_movimiento_positiva"
            ),
        ),
    ]
