# Generated by Django 5.2.9 on 2025-12-30 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventario", "0001_initial"),
        ("productos", "0002_alter_producto_codigo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="inventario",
            name="cantidad_reservada_no_negativa",
        ),
        migrations.RemoveField(
            model_name="inventario",
            name="cantidad_reservada",
        ),
        migrations.AlterField(
            model_name="inventario",
            name="cantidad_actual",
            field=models.IntegerField(default=0, verbose_name="Cantidad en Stock"),
        ),
        migrations.AlterField(
            model_name="inventario",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="inventario",
            name="producto",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inventario",
                to="productos.producto",
                verbose_name="Producto",
            ),
        ),
        migrations.AlterField(
            model_name="inventario",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="movimientoinventario",
            name="cantidad",
            field=models.IntegerField(verbose_name="Cantidad"),
        ),
        migrations.AlterField(
            model_name="movimientoinventario",
            name="motivo",
            field=models.TextField(blank=True, verbose_name="Motivo"),
        ),
        migrations.AlterField(
            model_name="movimientoinventario",
            name="tipo",
            field=models.CharField(
                choices=[("entrada", "Entrada"), ("salida", "Salida")],
                max_length=20,
                verbose_name="Tipo de Movimiento",
            ),
        ),
        migrations.AlterField(
            model_name="movimientoinventario",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario",
            ),
        ),
    ]
