# Generated by Django 5.2.9 on 2025-12-30 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("empresas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        blank=True,
                        help_text="Código único del producto (se genera automáticamente si está vacío)",
                        max_length=50,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre descriptivo del producto",
                        max_length=200,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        help_text="Descripción detallada del producto", verbose_name="Descripción"
                    ),
                ),
                (
                    "precio_usd",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Precio del producto en dólares estadounidenses",
                        max_digits=12,
                        verbose_name="Precio USD",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("fisico", "Físico"),
                            ("digital", "Digital"),
                            ("servicio", "Servicio"),
                        ],
                        default="fisico",
                        max_length=20,
                        verbose_name="Tipo de Producto",
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si el producto está activo para venta",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "stock_minimo",
                    models.IntegerField(
                        default=0,
                        help_text="Cantidad mínima de stock antes de reabastecimiento",
                        verbose_name="Stock Mínimo",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Fecha de actualización"),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        help_text="Empresa a la que pertenece el producto",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="productos",
                        to="empresas.empresa",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto",
                "verbose_name_plural": "Productos",
                "db_table": "productos",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["codigo"], name="productos_codigo_1fb639_idx"),
                    models.Index(fields=["nombre"], name="productos_nombre_d31432_idx"),
                    models.Index(fields=["empresa", "activo"], name="productos_empresa_ad276a_idx"),
                    models.Index(fields=["tipo"], name="productos_tipo_a03520_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("precio_usd__gt", 0)), name="precio_usd_positivo"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("stock_minimo__gte", 0)),
                        name="stock_minimo_no_negativo",
                    ),
                ],
            },
        ),
    ]
