# Generated by Django 5.2.9 on 2025-12-30 04:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("productos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="codigo",
            field=models.CharField(
                blank=True,
                help_text="Código único del producto (se genera automáticamente si está vacío)",
                max_length=50,
                unique=True,
                verbose_name="Código",
            ),
        ),
    ]
