# Generated by Django 5.2.9 on 2025-12-30 03:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "nit",
                    models.CharField(
                        help_text="Número de Identificación Tributaria",
                        max_length=15,
                        unique=True,
                        verbose_name="NIT",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Razón social de la empresa",
                        max_length=200,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "direccion",
                    models.TextField(
                        help_text="Dirección física de la empresa", verbose_name="Dirección"
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        help_text="Número de contacto principal",
                        max_length=20,
                        verbose_name="Teléfono",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Correo electrónico de contacto",
                        max_length=254,
                        verbose_name="Email",
                    ),
                ),
                (
                    "activa",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si la empresa está activa en el sistema",
                        verbose_name="Activa",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Fecha de actualización"),
                ),
            ],
            options={
                "verbose_name": "Empresa",
                "verbose_name_plural": "Empresas",
                "db_table": "empresas",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["nit"], name="empresas_nit_f247f8_idx"),
                    models.Index(fields=["nombre"], name="empresas_nombre_7f64b8_idx"),
                    models.Index(fields=["activa"], name="empresas_activa_0b856e_idx"),
                ],
            },
        ),
    ]
